services:
  app:
    build:
      context: .
    restart: always
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 10
    container_name: chat-ai-frontend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
