services:
  app:
    build:
      context: .
    restart: unless-stopped
    container_name: chat-ai-frontend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
